#route:
#    receiver: 'slack'
#
#receivers:
#    - name: 'slack'
#      slack_configs:
#          - send_resolved: true
#            text: "{{ .CommonAnnotations.description }}"
#            username: 'Prometheus'
#            channel: '#<channel-name>'
#            api_url: 'https://hooks.slack.com/services/<webhook-id>'

#global:
#resolve_timeout: 1m

route:
    receiver: 'gmail-notifications'

receivers:
    - name: 'gmail-notifications'
      email_configs:
          - to: sd.wanoon@gmail.com
            from: sd.wanoon@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: sd.wanoon@gmail.com
            auth_identity: sd.wanoon@gmail.com
            auth_password: dpvrsdavid
            send_resolved: true


